### ISSUE TITLE
I don't get it work at homeypro 2023

### ISSUE THREAD

**Issue by Barney1977** [halacs/BiSecur#1]
I installed the App
Created a new user in ios app ( username and WW )
I also visit bisecure homepage to create a new phone ID, set the accessrights 

I have doubt what to use as group ID. I can't find it in the app. It's numeric so i tried several numbers but until now nothing is working.

Can you please share more instructions/information about how to set up?

Kind regards

**Comment by halacs** [comment]
Hi,

My application/DSK is not complete yet.

This repository is intended to communicate with the BiSecur gateway directly without Hörmann's central cloud. You have a Horeman BiSecur gateway on your local network and you have to have a valid username and password pair to interact with it.

I am working on a software development kit to interact with the gateway and a linux command line application. No Android or IOS application is on the roadmap!

For more details please check the content of the repository.

Thank you for your understanding!
